/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batches */
        get: operations["batches_api_v1_batches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/batches/{batch_id}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Batch Results */
        get: operations["batch_results_api_v1_batches__batch_id__results_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decisions */
        get: operations["decisions_api_v1_decisions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/decisions/{decision_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Decision Detail */
        get: operations["decision_detail_api_v1_decisions__decision_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/escalations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Escalations */
        get: operations["escalations_api_v1_escalations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ledger/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ledger Status */
        get: operations["ledger_status_api_v1_ledger_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Versions */
        get: operations["versions_api_v1_meta_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/v1/playground": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_demo_v1_playground_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Scenario */
        post: operations["run_scenario_demo_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/demo/v1/runs/{run_id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Receipt */
        get: operations["download_receipt_demo_v1_runs__run_id__receipt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Live */
        get: operations["health_live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Ready */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/v1/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create */
        post: operations["create_simulator_v1_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detail */
        get: operations["detail_simulator_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/v1/runs/{run_id}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipt */
        get: operations["receipt_simulator_v1_runs__run_id__receipt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/v1/runs/{run_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync */
        post: operations["sync_simulator_v1_runs__run_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulator/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** State */
        get: operations["state_simulator_v1_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/razorpay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Razorpay Webhook */
        post: operations["razorpay_webhook_webhooks_razorpay_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/razorpay/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Webhook */
        post: operations["webhook_webhooks_razorpay_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ActionClass
         * @enum {string}
         */
        ActionClass: "A" | "B" | "C" | "D";
        /** AssumptionsOut */
        AssumptionsOut: {
            /** Note */
            note: string;
            /** Sensitivity Range Percent */
            sensitivity_range_percent: number;
            /** Version */
            version: string;
        };
        /** BatchListOut */
        BatchListOut: {
            /** Items */
            items: components["schemas"]["BatchOut"][];
        };
        /** BatchOut */
        BatchOut: {
            /** Batch Digest */
            batch_digest: string;
            /** Batch Id */
            batch_id: string;
            /** Created At */
            created_at: string;
            /** Scenario Count */
            scenario_count: number;
            /** Seed */
            seed: number;
        };
        /** BatchResultOut */
        BatchResultOut: {
            assumptions: components["schemas"]["AssumptionsOut"];
            /** Batch Digest */
            batch_digest: string;
            /** Batch Id */
            batch_id: string;
            /** Fallback Rate */
            fallback_rate: number;
            /** Fixed Clock */
            fixed_clock: string;
            /** Generated At */
            generated_at: string;
            /** Map Coverage Rate */
            map_coverage_rate: number;
            /** Policies */
            policies: components["schemas"]["PolicyMetricsOut"][];
            /** Real Vs Simulated */
            real_vs_simulated: string;
            /** Scenario Count */
            scenario_count: number;
            /** Schema Version */
            schema_version: string;
            /** Seed */
            seed: number;
            /** Sensitivity */
            sensitivity: components["schemas"]["SensitivityOut"][];
        };
        /** CloudExplanation */
        CloudExplanation: {
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "low" | "medium" | "high";
            /** Explanation */
            explanation: string;
            /** Operator Note */
            operator_note: string;
            suggested_class: components["schemas"]["ActionClass"];
        };
        /** CloudResult */
        CloudResult: {
            /**
             * Actor
             * @default local_operator
             * @constant
             */
            actor: "local_operator";
            /**
             * Cost Note
             * @default Not supplied by provider; check your Ollama plan quota.
             */
            cost_note: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
            /** Error Code */
            error_code?: string | null;
            /** Estimated Cost Usd */
            estimated_cost_usd?: number | null;
            /** Generated At */
            generated_at?: string | null;
            /** Generation Id */
            generation_id: string;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Model */
            model: string;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Prompt Fingerprint */
            prompt_fingerprint?: string | null;
            /**
             * Prompt Version
             * @default operator-explanation-v1
             */
            prompt_version: string;
            /**
             * Provider
             * @default ollama_cloud
             * @constant
             */
            provider: "ollama_cloud";
            result?: components["schemas"]["CloudExplanation"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "requesting" | "fresh" | "unavailable" | "invalid_response";
        };
        /** DecisionListOut */
        DecisionListOut: {
            /** Items */
            items: components["schemas"]["DecisionOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DecisionOut */
        DecisionOut: {
            /** Advisory Cache Key */
            advisory_cache_key: string | null;
            /** Advisory Class */
            advisory_class: string | null;
            /** Advisory Confidence */
            advisory_confidence: string | null;
            /** Advisory Provider */
            advisory_provider: string | null;
            /** Advisory Rationale */
            advisory_rationale: string | null;
            /** Allowed Actions */
            allowed_actions: string[];
            /** Amount Minor */
            amount_minor: number;
            /** Created At */
            created_at: string;
            /** Currency */
            currency: string;
            /** Decision Hash */
            decision_hash: string;
            /** Decision Id */
            decision_id: string;
            /** Decision Reasons */
            decision_reasons: string[];
            /** Effect Action */
            effect_action: string | null;
            /** Effect State */
            effect_state: string | null;
            /** Effective Class */
            effective_class: string;
            /** Event Id */
            event_id: string;
            /** Gate Checks */
            gate_checks: components["schemas"]["GateCheckOut"][];
            /** Idempotency Key */
            idempotency_key: string | null;
            /** Known Reason */
            known_reason: boolean;
            /** Method */
            method: string | null;
            /** Next Eligible At */
            next_eligible_at: string | null;
            /** Payment Id */
            payment_id: string;
            /** Policy Fingerprint */
            policy_fingerprint: string;
            /** Policy Version */
            policy_version: string;
            /** Reason */
            reason: string;
            /** Reason Map Fingerprint */
            reason_map_fingerprint: string;
            /** Review Required */
            review_required: boolean;
            /** Selected Action */
            selected_action: string;
            /** Triage Rationale */
            triage_rationale: string;
        };
        /** GateCheckOut */
        GateCheckOut: {
            /** Explanation */
            explanation: string;
            /** Name */
            name: string;
            /** Passed */
            passed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Details */
            details?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
        };
        /** LedgerOut */
        LedgerOut: {
            /** Entry Count */
            entry_count: number;
            /** Final Hash */
            final_hash: string | null;
            /** First Mismatch Sequence */
            first_mismatch_sequence: number | null;
            /** Valid */
            valid: boolean;
        };
        /** PlaygroundInput */
        PlaygroundInput: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Method
             * @default card
             * @enum {string}
             */
            method: "card" | "upi" | "netbanking";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "gateway_timeout" | "insufficient_funds" | "card_expired" | "risk_threshold" | "processor_code_z91";
        };
        /** PlaygroundReceipt */
        PlaygroundReceipt: {
            decision: components["schemas"]["DecisionOut"];
            /** Decision Count */
            decision_count: number;
            /** Duplicate */
            duplicate: boolean | null;
            /** Effect Count */
            effect_count: number;
            /** Elapsed Ms */
            elapsed_ms: number | null;
            /** Event Count */
            event_count: number;
            /** Ingress Verified */
            ingress_verified: boolean;
            /** Ledger Entry Count */
            ledger_entry_count: number;
            /** Ledger Valid */
            ledger_valid: boolean;
            request: components["schemas"]["PlaygroundInput"];
            /**
             * Safety Mode
             * @default dry_run
             * @constant
             */
            safety_mode: "dry_run";
        };
        /** PlaygroundScenario */
        PlaygroundScenario: {
            /** Description */
            description: string;
            /**
             * Id
             * @enum {string}
             */
            id: "gateway_timeout" | "insufficient_funds" | "card_expired" | "risk_threshold" | "processor_code_z91";
            /** Label */
            label: string;
        };
        /** PlaygroundState */
        PlaygroundState: {
            /** Recent */
            recent: components["schemas"]["DecisionOut"][];
            /** Remaining Runs */
            remaining_runs: number;
            /** Scenarios */
            scenarios: components["schemas"]["PlaygroundScenario"][];
        };
        /** PolicyMetricsOut */
        PolicyMetricsOut: {
            /** Attempts */
            attempts: number;
            /** Class D Violations */
            class_d_violations: number;
            /** Customer Contacts */
            customer_contacts: number;
            /** Decisions Digest */
            decisions_digest: string;
            /** Policy */
            policy: string;
            /** Recovered Count */
            recovered_count: number;
            /** Recovered Minor Units */
            recovered_minor_units: number;
            /** Recovered Minor Units Per Attempt */
            recovered_minor_units_per_attempt: number;
            /** Recovery Rate */
            recovery_rate: number;
            /** Scenario Count */
            scenario_count: number;
            /** Wasted Attempts */
            wasted_attempts: number;
        };
        /** RunInput */
        RunInput: {
            /** Amount Minor */
            amount_minor: number;
            /**
             * Method
             * @default card
             * @enum {string}
             */
            method: "card" | "upi" | "netbanking";
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Scenario
             * @default gateway_timeout
             * @enum {string}
             */
            scenario: "gateway_timeout" | "insufficient_funds" | "card_expired" | "risk_threshold" | "processor_code_z91";
            /**
             * Source
             * @enum {string}
             */
            source: "synthetic" | "razorpay_test";
        };
        /** RunOut */
        RunOut: {
            advice: components["schemas"]["CloudResult"] | null;
            /** Amount Minor */
            amount_minor: number;
            /** Checkout Key Id */
            checkout_key_id: string | null;
            /** Created At */
            created_at: string;
            decision: components["schemas"]["DecisionOut"] | null;
            /** Error Code */
            error_code: string | null;
            /** Event Source */
            event_source: string | null;
            /** Ledger Valid */
            ledger_valid: boolean;
            /** Method */
            method: string;
            /** Order Id */
            order_id: string | null;
            /** Payment Id */
            payment_id: string | null;
            /** Run Id */
            run_id: string;
            /**
             * Safety Mode
             * @default test_only_dry_run_recovery
             * @constant
             */
            safety_mode: "test_only_dry_run_recovery";
            /** Scenario */
            scenario: string;
            /** Source */
            source: string;
            /** Stage */
            stage: string;
            /** Webhook Deliveries */
            webhook_deliveries: number;
            /** Webhook Received */
            webhook_received: boolean;
        };
        /** SensitivityOut */
        SensitivityOut: {
            /** Batch Digest */
            batch_digest: string;
            /** Label */
            label: string;
            /** Policies */
            policies: components["schemas"]["PolicyMetricsOut"][];
            /** Probability Multiplier */
            probability_multiplier: number;
        };
        /** SimulatorState */
        SimulatorState: {
            /** Cloud Configured */
            cloud_configured: boolean;
            /** Cloud Model */
            cloud_model: string;
            /** Public Webhook Url */
            public_webhook_url: string | null;
            /** Razorpay Configured */
            razorpay_configured: boolean;
            /** Recent */
            recent: components["schemas"]["RunOut"][];
            /** Remaining Orders */
            remaining_orders: number;
            /** Remaining Runs */
            remaining_runs: number;
            /** Scenarios */
            scenarios: components["schemas"]["PlaygroundScenario"][];
            /** Webhook Received */
            webhook_received: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    batches_api_v1_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchListOut"];
                };
            };
        };
    };
    batch_results_api_v1_batches__batch_id__results_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decisions_api_v1_decisions_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionListOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decision_detail_api_v1_decisions__decision_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                decision_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalations_api_v1_escalations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionListOut"];
                };
            };
        };
    };
    ledger_status_api_v1_ledger_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LedgerOut"];
                };
            };
        };
    };
    versions_api_v1_meta_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    state_demo_v1_playground_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundState"];
                };
            };
        };
    };
    run_scenario_demo_v1_runs_post: {
        parameters: {
            query?: never;
            header?: {
                origin?: string | null;
                "x-salvage-playground"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaygroundInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_receipt_demo_v1_runs__run_id__receipt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaygroundReceipt"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    create_simulator_v1_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_simulator_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_simulator_v1_runs__run_id__receipt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_simulator_v1_runs__run_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    state_simulator_v1_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatorState"];
                };
            };
        };
    };
    razorpay_webhook_webhooks_razorpay_post: {
        parameters: {
            query?: never;
            header?: {
                "x-razorpay-signature"?: string | null;
                "x-razorpay-event-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    webhook_webhooks_razorpay_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
}
